/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DebateState = IDL.Record({
  'isDebating' : IDL.Bool,
  'transcript' : IDL.Text,
  'currentSpeaker' : IDL.Text,
});

export const idlService = IDL.Service({
  'abortDebate' : IDL.Func([IDL.Text], [], []),
  'getStatus' : IDL.Func([], [DebateState], ['query']),
  'startBoardroomDebate' : IDL.Func([IDL.Text], [], []),
  'topUpSwarm' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DebateState = IDL.Record({
    'isDebating' : IDL.Bool,
    'transcript' : IDL.Text,
    'currentSpeaker' : IDL.Text,
  });
  
  return IDL.Service({
    'abortDebate' : IDL.Func([IDL.Text], [], []),
    'getStatus' : IDL.Func([], [DebateState], ['query']),
    'startBoardroomDebate' : IDL.Func([IDL.Text], [], []),
    'topUpSwarm' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };