/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgentType = IDL.Variant({
  'cybersecurityToolbox' : IDL.Null,
  'dataAnalysis' : IDL.Null,
  'documentRouting' : IDL.Null,
  'decisionMaking' : IDL.Null,
  'generalPurpose' : IDL.Null,
  'archiveManagement' : IDL.Null,
  'contentGeneration' : IDL.Null,
  'researchLibrary' : IDL.Null,
  'fileOcrSystem' : IDL.Null,
  'mathLawAI' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'lastCycles' : IDL.Opt(IDL.Nat),
  'agentType' : IDL.Opt(AgentType),
  'isEnabled' : IDL.Bool,
  'principalId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FileMetadata = IDL.Record({
  'assignedAgent' : IDL.Text,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
});
export const DebateState = IDL.Record({
  'isDebating' : IDL.Bool,
  'emergencyMode' : IDL.Bool,
  'transcript' : IDL.Text,
  'currentSpeaker' : IDL.Text,
});
export const SensoryCortex = IDL.Service({
  'askAgent' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'abortDebate' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAgentRegistry' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileRegistry' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, FileMetadata))],
      ['query'],
    ),
  'getStatus' : IDL.Func([], [DebateState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAgents' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'routeDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, SensoryCortex],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startBoardroomDebate' : IDL.Func(
      [IDL.Text, SensoryCortex, SensoryCortex, SensoryCortex],
      [],
      [],
    ),
  'toggleAgentStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'topUpSwarm' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgentType = IDL.Variant({
    'cybersecurityToolbox' : IDL.Null,
    'dataAnalysis' : IDL.Null,
    'documentRouting' : IDL.Null,
    'decisionMaking' : IDL.Null,
    'generalPurpose' : IDL.Null,
    'archiveManagement' : IDL.Null,
    'contentGeneration' : IDL.Null,
    'researchLibrary' : IDL.Null,
    'fileOcrSystem' : IDL.Null,
    'mathLawAI' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'lastCycles' : IDL.Opt(IDL.Nat),
    'agentType' : IDL.Opt(AgentType),
    'isEnabled' : IDL.Bool,
    'principalId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FileMetadata = IDL.Record({
    'assignedAgent' : IDL.Text,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const DebateState = IDL.Record({
    'isDebating' : IDL.Bool,
    'emergencyMode' : IDL.Bool,
    'transcript' : IDL.Text,
    'currentSpeaker' : IDL.Text,
  });
  const SensoryCortex = IDL.Service({
    'askAgent' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'abortDebate' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAgentRegistry' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileRegistry' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, FileMetadata))],
        ['query'],
      ),
    'getStatus' : IDL.Func([], [DebateState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAgents' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'routeDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, SensoryCortex],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startBoardroomDebate' : IDL.Func(
        [IDL.Text, SensoryCortex, SensoryCortex, SensoryCortex],
        [],
        [],
      ),
    'toggleAgentStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'topUpSwarm' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };