/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : bigint,
  'name' : string,
  'lastCycles' : [] | [bigint],
  'agentType' : [] | [AgentType],
  'isEnabled' : boolean,
  'principalId' : [] | [string],
}
export type AgentType = { 'cybersecurityToolbox' : null } |
  { 'dataAnalysis' : null } |
  { 'documentRouting' : null } |
  { 'decisionMaking' : null } |
  { 'generalPurpose' : null } |
  { 'archiveManagement' : null } |
  { 'contentGeneration' : null } |
  { 'researchLibrary' : null } |
  { 'fileOcrSystem' : null } |
  { 'mathLawAI' : null };
export interface DebateState {
  'isDebating' : boolean,
  'emergencyMode' : boolean,
  'transcript' : string,
  'currentSpeaker' : string,
}
export interface FileMetadata {
  'assignedAgent' : string,
  'size' : bigint,
  'filename' : string,
}
export interface SensoryCortex { 'askAgent' : ActorMethod<[string], string> }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'abortDebate' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAgentRegistry' : ActorMethod<[], Array<Agent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileRegistry' : ActorMethod<[], Array<[string, FileMetadata]>>,
  'getStatus' : ActorMethod<[], DebateState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAgents' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'routeDocument' : ActorMethod<[string, string, bigint, Principal], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startBoardroomDebate' : ActorMethod<
    [string, Principal, Principal, Principal],
    undefined
  >,
  'toggleAgentStatus' : ActorMethod<[string, boolean], undefined>,
  'topUpSwarm' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];